/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import classes.Configuracion;
import classes.VehiclePlant;
import javax.swing.JSpinner;
import productores.TipoWorker;

/**
 *
 * @author mannith
 */
public class Dashboard extends javax.swing.JFrame {
    int[] valoresIniciales =  Configuracion.leerDatosIniciales(); //valoresIniciales[0]:duracion dia, [1]:dias para entrega
    VehiclePlant LamboPlant = new VehiclePlant("Lamborghini", 11, valoresIniciales[0], valoresIniciales[1], true);

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.qtyWChasis.setValue(LamboPlant.emplPorDepto[0]);
        this.qtyWCarroceria.setValue(LamboPlant.emplPorDepto[1]);
        this.qtyWMotor.setValue(LamboPlant.emplPorDepto[2]);
        this.qtyWAcc.setValue(LamboPlant.emplPorDepto[3]);
        this.qtyWRuedas.setValue(LamboPlant.emplPorDepto[4]);
        this.qtyWEnsamblador.setValue(LamboPlant.emplPorDepto[5]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qtyWChasis = new javax.swing.JSpinner();
        workerChasis = new javax.swing.JLabel();
        workerCarroceria = new javax.swing.JLabel();
        qtyWMotor = new javax.swing.JSpinner();
        workerMotor = new javax.swing.JLabel();
        qtyWCarroceria = new javax.swing.JSpinner();
        workerRuedas = new javax.swing.JLabel();
        qtyWRuedas = new javax.swing.JSpinner();
        workerAcc = new javax.swing.JLabel();
        qtyWAcc = new javax.swing.JSpinner();
        workerEnsamblador = new javax.swing.JLabel();
        qtyWEnsamblador = new javax.swing.JSpinner();
        startPlant = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        qtyAcc = new javax.swing.JTextField();
        qtyChasis = new javax.swing.JTextField();
        qtyCarroceria = new javax.swing.JTextField();
        qtyMotores = new javax.swing.JTextField();
        qtyCarrosProducidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        qtyRuedas1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        qtyCarrosProducidos1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        qtyCarrosProducidos2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        diasTotales = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sueldoMensual = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        directorAccion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        gerenteAccion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        empleadosDispo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        gananciaNeta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        qtyCarrosProducidos3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qtyWChasis.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWChasis.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWChasisStateChanged(evt);
            }
        });
        getContentPane().add(qtyWChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        workerChasis.setText("Trabajadores de Chasis:");
        getContentPane().add(workerChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        workerCarroceria.setText("Trabajadores de Carroceria:");
        getContentPane().add(workerCarroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        qtyWMotor.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(qtyWMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        workerMotor.setText("Trabajadores de Motor:");
        getContentPane().add(workerMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        qtyWCarroceria.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWCarroceria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWCarroceriaStateChanged(evt);
            }
        });
        getContentPane().add(qtyWCarroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        workerRuedas.setText("Trabajadores de Ruedas:");
        getContentPane().add(workerRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        qtyWRuedas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(qtyWRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        workerAcc.setText("Trabajadores de Accesorios:");
        getContentPane().add(workerAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        qtyWAcc.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(qtyWAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        workerEnsamblador.setText("Ensambladores:");
        getContentPane().add(workerEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        qtyWEnsamblador.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(qtyWEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        startPlant.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        startPlant.setText("Iniciar Simulacion");
        startPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPlantActionPerformed(evt);
            }
        });
        getContentPane().add(startPlant, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 27, 270, 59));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jLabel7.setText("Almacen");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, 60));

        qtyAcc.setText("0");
        getContentPane().add(qtyAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 30, -1));

        qtyChasis.setText("0");
        getContentPane().add(qtyChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 30, -1));

        qtyCarroceria.setText("0");
        qtyCarroceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyCarroceriaActionPerformed(evt);
            }
        });
        getContentPane().add(qtyCarroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 30, -1));

        qtyMotores.setText("0");
        getContentPane().add(qtyMotores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 30, -1));

        qtyCarrosProducidos.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        qtyCarrosProducidos.setText("0");
        getContentPane().add(qtyCarrosProducidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 50, 40));

        jLabel8.setText("Set Accesorios");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel9.setText("Chasis");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel10.setText("Carroceria");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel11.setText("Motores");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jLabel12.setText("Ruedas");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel13.setText("Carros Vendidos:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        qtyRuedas1.setText("0");
        getContentPane().add(qtyRuedas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 30, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel14.setText("Dias para la entrega:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        qtyCarrosProducidos1.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        qtyCarrosProducidos1.setText("7");
        qtyCarrosProducidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyCarrosProducidos1ActionPerformed(evt);
            }
        });
        getContentPane().add(qtyCarrosProducidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 50, 40));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel15.setText("Carros Producidos:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        qtyCarrosProducidos2.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        qtyCarrosProducidos2.setText("0");
        getContentPane().add(qtyCarrosProducidos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 50, 40));

        jLabel16.setText("Dias Totales:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        diasTotales.setText("0");
        diasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasTotalesActionPerformed(evt);
            }
        });
        getContentPane().add(diasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 30, -1));

        jLabel17.setText("Sueldo Mensual:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        sueldoMensual.setText("0");
        sueldoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoMensualActionPerformed(evt);
            }
        });
        getContentPane().add(sueldoMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 60, -1));

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 2, 30)); // NOI18N
        jLabel18.setText("Planta ###");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel19.setText("Director de la planta esta actualmente:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        directorAccion.setText("Accion");
        directorAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorAccionActionPerformed(evt);
            }
        });
        getContentPane().add(directorAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 160, -1));

        jLabel20.setText("Gerente de la planta esta actualmente:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 40));

        gerenteAccion.setText("Accion");
        gerenteAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenteAccionActionPerformed(evt);
            }
        });
        getContentPane().add(gerenteAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 160, -1));

        jLabel21.setText("Empleados disponibles");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        empleadosDispo.setText("0");
        empleadosDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosDispoActionPerformed(evt);
            }
        });
        getContentPane().add(empleadosDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 30, -1));

        jLabel22.setText("Ganancia neta:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        gananciaNeta.setText("0");
        gananciaNeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciaNetaActionPerformed(evt);
            }
        });
        getContentPane().add(gananciaNeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 60, -1));

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel23.setText("Ganancia Total:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        qtyCarrosProducidos3.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        qtyCarrosProducidos3.setText("0");
        getContentPane().add(qtyCarrosProducidos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startPlantActionPerformed

    private void qtyCarroceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyCarroceriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyCarroceriaActionPerformed

    private void qtyCarrosProducidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyCarrosProducidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyCarrosProducidos1ActionPerformed

    private void diasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasTotalesActionPerformed

    private void sueldoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoMensualActionPerformed

    private void directorAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directorAccionActionPerformed

    private void gerenteAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenteAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenteAccionActionPerformed

    private void empleadosDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadosDispoActionPerformed

    private void gananciaNetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciaNetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaNetaActionPerformed

    private void qtyWChasisStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWChasisStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWChasis.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.chasis, valor);
        this.qtyWChasis.setValue(valor);
    }//GEN-LAST:event_qtyWChasisStateChanged

    private void qtyWCarroceriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWCarroceriaStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWCarroceria.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.carroceria, valor);
        this.qtyWCarroceria.setValue(valor);
    }//GEN-LAST:event_qtyWCarroceriaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diasTotales;
    private javax.swing.JTextField directorAccion;
    private javax.swing.JTextField empleadosDispo;
    private javax.swing.JTextField gananciaNeta;
    private javax.swing.JTextField gerenteAccion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField qtyAcc;
    private javax.swing.JTextField qtyCarroceria;
    private javax.swing.JTextField qtyCarrosProducidos;
    private javax.swing.JTextField qtyCarrosProducidos1;
    private javax.swing.JTextField qtyCarrosProducidos2;
    private javax.swing.JTextField qtyCarrosProducidos3;
    private javax.swing.JTextField qtyChasis;
    private javax.swing.JTextField qtyMotores;
    private javax.swing.JTextField qtyRuedas1;
    private javax.swing.JSpinner qtyWAcc;
    private javax.swing.JSpinner qtyWCarroceria;
    private javax.swing.JSpinner qtyWChasis;
    private javax.swing.JSpinner qtyWEnsamblador;
    private javax.swing.JSpinner qtyWMotor;
    private javax.swing.JSpinner qtyWRuedas;
    private javax.swing.JToggleButton startPlant;
    private javax.swing.JTextField sueldoMensual;
    private javax.swing.JLabel workerAcc;
    private javax.swing.JLabel workerCarroceria;
    private javax.swing.JLabel workerChasis;
    private javax.swing.JLabel workerEnsamblador;
    private javax.swing.JLabel workerMotor;
    private javax.swing.JLabel workerRuedas;
    // End of variables declaration//GEN-END:variables
}
