/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dashboard;

/**
 *
 * @author Juan
 */
public class DashboardInfo extends javax.swing.JPanel {

    /**
     * Creates new form DashboardInfo
     */
    public DashboardInfo() {
        initComponents();
    }
    
    public void setUtilidadTotal(int num){
        String cant = Integer.toString(num);
        this.utilidadTotal.setText(cant);
    }
    public void setGananciaNeta(int num){
        String cant = Integer.toString(num);
        this.gananciaNeta.setText(cant);
    }
    public void setSueldosLabel(int num){
        String cant = Integer.toString(num);
        this.SueldosLabel.setText(cant);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        gananciaNeta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        utilidadTotal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        SueldosLabel = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setText("Ganancia en bruto:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));

        gananciaNeta.setEditable(false);
        gananciaNeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gananciaNeta.setText("0");
        gananciaNeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciaNetaActionPerformed(evt);
            }
        });
        add(gananciaNeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, -1));

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel23.setText("Utilidad Total:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        utilidadTotal.setEditable(false);
        utilidadTotal.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        utilidadTotal.setText("0");
        add(utilidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 140, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel28.setText("Costos (Sueldos):");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, -1));

        SueldosLabel.setEditable(false);
        SueldosLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SueldosLabel.setText("0");
        SueldosLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SueldosLabelActionPerformed(evt);
            }
        });
        add(SueldosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void gananciaNetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciaNetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaNetaActionPerformed

    private void SueldosLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SueldosLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SueldosLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SueldosLabel;
    private javax.swing.JTextField gananciaNeta;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JTextField utilidadTotal;
    // End of variables declaration//GEN-END:variables
}
