/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dashboard;

import classes.Configuracion;
import classes.VehiclePlant;
import javax.swing.JLabel;
import productores.TipoWorker;


/**
 *
 * @author Juan
 */
public class LGdashboard extends javax.swing.JPanel {
    VehiclePlant LamboPlant;
//    public static int[] valoresIniciales =  Configuracion.leerDatosIniciales();
//    VehiclePlant LamboPlant = new VehiclePlant("Lamborghini", 11, valoresIniciales[0], valoresIniciales[1], true);
    
    /**
     * Creates new form a
     */
    public LGdashboard() {
        initComponents();
    }
    
    public void setLamboPlant(VehiclePlant LamboPlant){
        this.LamboPlant = LamboPlant;
        setWorkersSpinners();
        setWorkersLeft();
    }
    
    public void setWorkersLeft(){
        int cantidadActual = Functions.calcWorkersQty(LamboPlant.emplPorDepto);
        int restan = LamboPlant.maxWorkerQty - cantidadActual;
        this.empleadosDispo.setText(Integer.toString(restan));
    }
    
    public void setWorkersSpinners(){
        this.qtyWChasis.setValue(LamboPlant.emplPorDepto[0]);
        this.qtyWCarroceria.setValue(LamboPlant.emplPorDepto[1]);
        this.qtyWMotor.setValue(LamboPlant.emplPorDepto[2]);
        this.qtyWAcc.setValue(LamboPlant.emplPorDepto[3]);
        this.qtyWRuedas.setValue(LamboPlant.emplPorDepto[4]);
        this.qtyWEnsamblador.setValue(LamboPlant.emplPorDepto[5]);
    }
    
    public void setChasisQtyLabel(int num){
        String cant = Integer.toString(num);
        this.qtyChasis.setText(cant);
    }
    public void setCarrQtyLabel(int num){
        String cant = Integer.toString(num);
        this.qtyCarroceria.setText(cant);
    }
    public void setMotorQtyLabel(int num){
        String cant = Integer.toString(num);
        this.qtyMotores.setText(cant);
    }
    public void setRuedasQtyLabel(int num){
        String cant = Integer.toString(num);
        this.qtyRuedas.setText(cant);
    }
    public void setAccQtyLabel(int num){
        String cant = Integer.toString(num);
        this.qtyAcc.setText(cant);
    }
    public void setQtyCarrosProd(int num){
        String cant = Integer.toString(num);
        this.qtyCarrosProducidos.setText(cant);
    }
    public void setQtyCarrosAccProd(int num){
        String cant = Integer.toString(num);
        this.qtyCarrosAccProducidos.setText(cant);
    }
    public void setValoresAlmacen(int chasis, int carr, int motor, int ruedas, int acc){
        String newChasis = Integer.toString(chasis);
        String newCarr = Integer.toString(carr);
        String newMotor = Integer.toString(motor);
        String newRuedas = Integer.toString(ruedas);
        String newAcc = Integer.toString(acc);
        
        this.qtyChasis.setText(newChasis);
        this.qtyCarroceria.setText(newCarr);
        this.qtyMotores.setText(newMotor);
        this.qtyRuedas.setText(newRuedas);
        this.qtyAcc.setText(newAcc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qtyWChasis = new javax.swing.JSpinner();
        workerChasis = new javax.swing.JLabel();
        workerCarroceria = new javax.swing.JLabel();
        qtyWMotor = new javax.swing.JSpinner();
        workerMotor = new javax.swing.JLabel();
        qtyWCarroceria = new javax.swing.JSpinner();
        workerRuedas = new javax.swing.JLabel();
        qtyWRuedas = new javax.swing.JSpinner();
        workerAcc = new javax.swing.JLabel();
        qtyWAcc = new javax.swing.JSpinner();
        workerEnsamblador = new javax.swing.JLabel();
        qtyWEnsamblador = new javax.swing.JSpinner();
        startPlant = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        diasTotales = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sueldoMensual = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        directorAccion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        gerenteAccion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        gananciaNeta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        qtyCarrosProducidos3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtyChasis = new javax.swing.JLabel();
        qtyCarroceria = new javax.swing.JLabel();
        qtyMotores = new javax.swing.JLabel();
        qtyRuedas = new javax.swing.JLabel();
        qtyAcc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        empleadosDispo = new javax.swing.JLabel();
        qtyCarrosProducidos = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        qtyCarrosAccProducidos = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qtyWChasis.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWChasis.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWChasisStateChanged(evt);
            }
        });
        add(qtyWChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        workerChasis.setText("Trabajadores de Chasis:");
        add(workerChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        workerCarroceria.setText("Trabajadores de Carroceria:");
        add(workerCarroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        qtyWMotor.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWMotor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWMotorStateChanged(evt);
            }
        });
        add(qtyWMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        workerMotor.setText("Trabajadores de Motor:");
        add(workerMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        qtyWCarroceria.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWCarroceria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWCarroceriaStateChanged(evt);
            }
        });
        add(qtyWCarroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        workerRuedas.setText("Trabajadores de Ruedas:");
        add(workerRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        qtyWRuedas.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWRuedas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWRuedasStateChanged(evt);
            }
        });
        add(qtyWRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        workerAcc.setText("Trabajadores de Accesorios:");
        add(workerAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        qtyWAcc.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWAcc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWAccStateChanged(evt);
            }
        });
        add(qtyWAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        workerEnsamblador.setText("Ensambladores:");
        add(workerEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        qtyWEnsamblador.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        qtyWEnsamblador.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyWEnsambladorStateChanged(evt);
            }
        });
        add(qtyWEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        startPlant.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        startPlant.setText("Iniciar Simulacion");
        startPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPlantActionPerformed(evt);
            }
        });
        add(startPlant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 59));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jLabel7.setText("Almacen");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Set Accesorios");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Chasis");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Carroceria");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Motores");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Ruedas");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel13.setText("Carros Vendidos:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel14.setText("Dias para la entrega:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel15.setText("Carros Producidos:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        jLabel16.setText("Dias Totales:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        diasTotales.setText("0");
        diasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasTotalesActionPerformed(evt);
            }
        });
        add(diasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 30, -1));

        jLabel17.setText("Sueldo Mensual:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        sueldoMensual.setText("0");
        sueldoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoMensualActionPerformed(evt);
            }
        });
        add(sueldoMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 60, -1));

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 2, 30)); // NOI18N
        jLabel18.setText("Planta ###");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel19.setText("Director de la planta esta actualmente:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        directorAccion.setText("Accion");
        directorAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorAccionActionPerformed(evt);
            }
        });
        add(directorAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 160, -1));

        jLabel20.setText("Gerente de la planta esta actualmente:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 40));

        gerenteAccion.setText("Accion");
        gerenteAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenteAccionActionPerformed(evt);
            }
        });
        add(gerenteAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 160, -1));

        jLabel21.setText("Empleados disponibles:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 20));

        jLabel22.setText("Ganancia neta:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        gananciaNeta.setText("0");
        gananciaNeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciaNetaActionPerformed(evt);
            }
        });
        add(gananciaNeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 60, -1));

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jLabel23.setText("Ganancia Total:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        qtyCarrosProducidos3.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        qtyCarrosProducidos3.setText("0");
        add(qtyCarrosProducidos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 110, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Máximo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Disponible");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        qtyChasis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyChasis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyChasis.setText("0");
        add(qtyChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 20, -1));

        qtyCarroceria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyCarroceria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyCarroceria.setText("0");
        add(qtyCarroceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 30, -1));

        qtyMotores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyMotores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyMotores.setText("0");
        add(qtyMotores, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 30, -1));

        qtyRuedas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyRuedas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyRuedas.setText("0");
        add(qtyRuedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 30, -1));

        qtyAcc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyAcc.setText("0");
        add(qtyAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 30, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("25");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 20, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("20");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 20, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("55");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 40, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("35");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 20, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("10");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 20, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 80, -1));

        empleadosDispo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empleadosDispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleadosDispo.setText("0");
        add(empleadosDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 30, -1));

        qtyCarrosProducidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyCarrosProducidos.setText("0");
        add(qtyCarrosProducidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 40, 20));

        jLabel25.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel25.setText("Con accesorios:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 120, 30));

        jLabel26.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel26.setText("Normales:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, 20));

        qtyCarrosAccProducidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtyCarrosAccProducidos.setText("0");
        add(qtyCarrosAccProducidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 40, 30));

        jLabel27.setText("Faltas:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel28.setText("0");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 20, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void qtyWChasisStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWChasisStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWChasis.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.chasis, valor);
        this.qtyWChasis.setValue(valor);
        this.setWorkersLeft();
    }//GEN-LAST:event_qtyWChasisStateChanged

    private void qtyWMotorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWMotorStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWMotor.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.motor, valor);
        this.qtyWMotor.setValue(valor);
        this.setWorkersLeft();
    }//GEN-LAST:event_qtyWMotorStateChanged

    private void qtyWCarroceriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWCarroceriaStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWCarroceria.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.carroceria, valor);
        this.qtyWCarroceria.setValue(valor);
        this.setWorkersLeft();
    }//GEN-LAST:event_qtyWCarroceriaStateChanged

    private void qtyWRuedasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWRuedasStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWRuedas.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.ruedas, valor);
        this.qtyWRuedas.setValue(valor);
        this.setWorkersLeft();
    }//GEN-LAST:event_qtyWRuedasStateChanged

    private void qtyWAccStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWAccStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWAcc.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.accesorios, valor);
        this.qtyWAcc.setValue(valor);
        this.setWorkersLeft();
    }//GEN-LAST:event_qtyWAccStateChanged

    private void qtyWEnsambladorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyWEnsambladorStateChanged
        // TODO add your handling code here:
        int valor = Integer.parseInt(this.qtyWEnsamblador.getValue().toString());
        // validar valor para ver si no excede limite de workers
        valor = Functions.validarCantEmpl(LamboPlant, TipoWorker.ensamblador, valor);
        this.qtyWEnsamblador.setValue(valor);
        this.setWorkersLeft();
    }//GEN-LAST:event_qtyWEnsambladorStateChanged

    private void startPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPlantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startPlantActionPerformed

    private void diasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasTotalesActionPerformed

    private void sueldoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoMensualActionPerformed

    private void directorAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directorAccionActionPerformed

    private void gerenteAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenteAccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerenteAccionActionPerformed

    private void gananciaNetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciaNetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gananciaNetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diasTotales;
    private javax.swing.JTextField directorAccion;
    private javax.swing.JLabel empleadosDispo;
    private javax.swing.JTextField gananciaNeta;
    private javax.swing.JTextField gerenteAccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel qtyAcc;
    private javax.swing.JLabel qtyCarroceria;
    private javax.swing.JLabel qtyCarrosAccProducidos;
    private javax.swing.JLabel qtyCarrosProducidos;
    private javax.swing.JTextField qtyCarrosProducidos3;
    private javax.swing.JLabel qtyChasis;
    private javax.swing.JLabel qtyMotores;
    private javax.swing.JLabel qtyRuedas;
    private javax.swing.JSpinner qtyWAcc;
    private javax.swing.JSpinner qtyWCarroceria;
    private javax.swing.JSpinner qtyWChasis;
    private javax.swing.JSpinner qtyWEnsamblador;
    private javax.swing.JSpinner qtyWMotor;
    private javax.swing.JSpinner qtyWRuedas;
    private javax.swing.JToggleButton startPlant;
    private javax.swing.JTextField sueldoMensual;
    private javax.swing.JLabel workerAcc;
    private javax.swing.JLabel workerCarroceria;
    private javax.swing.JLabel workerChasis;
    private javax.swing.JLabel workerEnsamblador;
    private javax.swing.JLabel workerMotor;
    private javax.swing.JLabel workerRuedas;
    // End of variables declaration//GEN-END:variables

    public JLabel getQtyChasis() {
        return qtyChasis;
    }
    public JLabel getQtyCarroceria() {
        return this.qtyCarroceria;
    } 
    public JLabel getQtyMotor() {
        return this.qtyMotores;
    }
    public JLabel getQtyRuedas() {
        return this.qtyRuedas;
    }
    public JLabel getQtyAcc() {
        return this.qtyAcc;
    }

}
